### ISSUE TITLE
question about requirement 

### ISSUE THREAD

**Issue by MED-YAHYAOUI** [mshaikh2/AttentionHandwritingVerification#1]
hello, which version of keras and tensorflow do you use for this project and please can i run it on colab ,

**Comment by mshaikh2** [comment]
Hi, I used 2.2.4 keras and 1.15 tensorflow version:
Yes it can run on colab, you will have to configure the environment and add the imports manually or in a cell

**Comment by MED-YAHYAOUI** [comment]
Yes thank you.  I tried to do that , and it found a problem at multi-gpu.  Because colabe has just 1 gpu.  

To keep you updated.  
Im working on a offline handwriting signature verification , and i have intention to use your work as a base to learn this kind of attention based solution, 
I'd be very happy if you can help me.

**Comment by mshaikh2** [comment]
You can easily replace the multi_gpu lines of codes from the model generation. That should work. Please post any specific errors and I will help

**Comment by MED-YAHYAOUI** [comment]
thank you , i just solve the problem , i have a quation please , 
how can i use that with my main problem , signature verification ,i want to know if  2 signature are from the same writer or not,
thanks for your help again

**Comment by MED-YAHYAOUI** [comment]
or how can i pass a cedar image to this algorithme for ploting  the attention map , and classify it either real or forgrie

**Comment by mshaikh2** [comment]
Great if the main issue is resolved we can mark this closed. The signature images can be passed as inputs the same way `and` images are, however, you will need to resize the signature images to make it square or some standard dimension.
